### ISSUE TITLE
authentication broken?

### ISSUE THREAD

**Issue by 88gts** [snjoetw/py-august#65]
been following a routine process to update creds when they expire, can no longer get beyond the following to generate a new token.  thoughts?

authentication = authenticator.authenticate()

Token has expired.
Traceback (most recent call last):
  File "creds.py", line 26, in <module>
    authenticator.send_verification_code()
  File "/var/www/scripts/george/py-august/august/authenticator.py", line 102, in send_verification_code
    self._authentication.access_token, self._login_method, self._username
  File "/var/www/scripts/george/py-august/august/api.py", line 44, in send_verification_code
    access_token, login_method, username
  File "/var/www/scripts/george/py-august/august/api.py", line 239, in _dict_to_api
    _raise_response_exceptions(response)
  File "/var/www/scripts/george/py-august/august/api.py", line 273, in _raise_response_exceptions
    raise err
  File "/var/www/scripts/george/py-august/august/api.py", line 246, in _raise_response_exceptions
    response.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api-production.august.com/validation/phone

**Comment by 88gts** [comment]
Use email instead of phone in authenticator, works.

https://github.com/home-assistant/core/issues/77054
