### ISSUE TITLE
Errors coming from lock module

### ISSUE THREAD

**Issue by Jefronty** [snjoetw/py-august#7]
I was able to successfully sign-in with this package, and view house data in both `get_houses` and `get_house` but any time I try to access lock info I get an uncaught error  
`api.get_locks( authentication.access_token )`  
```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/august/api.py", line 195, in get_locks
    return [Lock(device_id, data) for device_id, data in json.items()]
  File "/usr/local/lib/python2.7/dist-packages/august/lock.py", line 8, in __init__
    super().__init__(
TypeError: super() takes at least 1 argument (0 given)
```
`api.get_operable_locks(authentication.access_token)`  
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/august/api.py", line 198, in get_operable_locks
    locks = self.get_locks(access_token)
  File "/usr/local/lib/python2.7/dist-packages/august/api.py", line 195, in get_locks
    return [Lock(device_id, data) for device_id, data in json.items()]
  File "/usr/local/lib/python2.7/dist-packages/august/lock.py", line 8, in __init__
    super().__init__(
TypeError: super() takes at least 1 argument (0 given)
```
`api.get_lock_detail(authentication.access_token, 'LOCK_ID_FROM_get_house')`  
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/august/api.py", line 208, in get_lock_detail
    return LockDetail(response.json())
  File "/usr/local/lib/python2.7/dist-packages/august/lock.py", line 29, in __init__
    super().__init__(
TypeError: super() takes at least 1 argument (0 given)
```

Although I can get the lock_id from the house info, and `get_lock_status`, `get_lock_door_status`, `lock`, and `unlock`  do seem to work.

**Comment by snjoetw** [comment]
As @qubidt answered, this is due to incorrect python version being used
